User.create(name: "Laura")
User.create(name: "Amanda")
User.create(name: "Jay")
User.create(name: "Jeff")
User.create(name: "Sam")
User.create(name: "Leigh")
User.create(name: "Maralynn")
User.create(name: "Elisa")
User.create(name: "Robin")
User.create(name: "Peter")
User.create(name: "Tom")
User.create(name: "Perry")
User.create(name: "Phillip")
User.create(name: "Dazzy")

Category.create(name: "Coffee")
first = Category.first 
Restaurant.create(name: "Kitchen", address: "11 Broadway", rating: 3.14, categories: [first])

UserRestaurant.create(restaurant_id: 1, user_id: 1, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 2, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 3, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 4, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 5, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 6, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 7, been_there: false)
UserRestaurant.create(restaurant_id: 1, user_id: 8, been_there: false)

UserRestaurant.create(restaurant_id: 1, user_id: 9, been_there: true)
UserRestaurant.create(restaurant_id: 1, user_id: 10, been_there: true)
UserRestaurant.create(restaurant_id: 1, user_id: 11, been_there: true)
UserRestaurant.create(restaurant_id: 1, user_id: 12, been_there: true)
UserRestaurant.create(restaurant_id: 1, user_id: 13, been_there: true)
UserRestaurant.create(restaurant_id: 1, user_id: 14, been_there: true)
